// Delhi-NCR service areas (client list, 51 locations). Applied once by scripts/seed.mjs; editable in Admin → Locations.
// Notes stay factual and general: Edexo's centres are in Rohini and Dwarka only — pages never claim a centre in each area.

// Cluster labels and default audiences live in src/lib/locations.ts.

// [name, cluster, area note]
export const locations = [
  ['Rohini', 'rohini', 'Rohini is one of the largest residential areas of North-West Delhi — and home to our Edexo Rohini centre on Outer Ring Road, Prashant Vihar, Sector 14.'],
  ['Pitampura', 'rohini', 'Pitampura sits right next to Rohini and Prashant Vihar, so our Rohini centre is a short trip away for most learners in the area.'],
  ['Shalimar Bagh', 'rohini', 'Shalimar Bagh is a well-established residential area in North-West Delhi, a short distance from our Rohini centre.'],
  ['Prashant Vihar', 'rohini', 'Our Edexo Rohini centre is located in Prashant Vihar (A-1/1, Outer Ring Road, Sector 14) — so learners here can simply walk in for a free demo class.'],
  ['Ashok Vihar', 'rohini', 'Ashok Vihar is a residential neighbourhood in North-West Delhi with easy road access to our Rohini centre.'],
  ['Wazirpur', 'rohini', 'Wazirpur, with its residential colonies and industrial area, is close to Ashok Vihar and Shalimar Bagh — within easy reach of our Rohini centre.'],
  ['Model Town', 'campus', 'Model Town is a residential area of North Delhi, close to the Delhi University North Campus belt.'],
  ['Mukherjee Nagar', 'campus', 'Mukherjee Nagar is well known as a hub for students and competitive-exam aspirants in North Delhi, close to the University North Campus.'],
  ['GTB Nagar', 'campus', 'GTB Nagar is a busy student area right beside the Delhi University North Campus.'],
  ['Kamla Nagar', 'campus', 'Kamla Nagar, next to the Delhi University North Campus, is popular with college students from across the city.'],
  ['Shakti Nagar', 'campus', 'Shakti Nagar is a residential area near Kamla Nagar and the Delhi University North Campus.'],
  ['Adarsh Nagar', 'campus', 'Adarsh Nagar is a residential area of North-West Delhi near Azadpur and Model Town.'],
  ['Azadpur', 'campus', 'Azadpur, in North-West Delhi, sits between Model Town, Adarsh Nagar and Shalimar Bagh.'],
  ['Jahangirpuri', 'outerNorth', 'Jahangirpuri is a large residential area in North-West Delhi, near Adarsh Nagar and Azadpur.'],
  ['Bhalswa', 'outerNorth', 'Bhalswa, in North-West Delhi, is close to Jahangirpuri and Mukundpur.'],
  ['Burari', 'outerNorth', 'Burari is a fast-growing residential area of North Delhi with many families and students.'],
  ['Sant Nagar', 'outerNorth', 'Sant Nagar is a residential locality in the Burari area of North Delhi.'],
  ['Mukundpur', 'outerNorth', 'Mukundpur is a residential area of North Delhi near Bhalswa and Jahangirpuri.'],
  ['Budh Vihar', 'outerRohini', 'Budh Vihar is a residential area on the western side of Rohini in North-West Delhi.'],
  ['Prem Nagar', 'outerRohini', 'Prem Nagar is a residential locality in the outer Rohini area of North-West Delhi.'],
  ['Vijay Vihar', 'outerRohini', 'Vijay Vihar is a residential area near Rohini in North-West Delhi.'],
  ['Rithala', 'outerRohini', 'Rithala lies on the north-western edge of Rohini in North-West Delhi.'],
  ['Begumpur', 'outerRohini', 'Begumpur is a residential area in the outer Rohini region of North-West Delhi.'],
  ['Sultanpuri', 'outerRohini', 'Sultanpuri is a residential area of North-West Delhi near Mangolpuri and Rohini.'],
  ['Mangolpuri', 'outerRohini', 'Mangolpuri is a residential area of North-West Delhi bordering Rohini and Sultanpuri.'],
  ['Kirari', 'outerRohini', 'Kirari is a large residential area in North-West Delhi near Prem Nagar and Aman Vihar.'],
  ['Pooth Kalan', 'outerRohini', 'Pooth Kalan is an urban village and residential area on the western side of Rohini.'],
  ['Narela', 'outerNorth', 'Narela is a sub-city of North Delhi with growing residential sectors and an industrial area.'],
  ['Bawana', 'outerNorth', 'Bawana, in outer North-West Delhi, is known for its industrial area and nearby residential colonies.'],
  ['Alipur', 'outerNorth', 'Alipur is a town in North Delhi on the way towards Narela.'],
  ['Shahbad Dairy', 'outerNorth', 'Shahbad Dairy is a residential area in North-West Delhi near Rohini and Samaypur Badli.'],
  ['Samaypur Badli', 'outerNorth', 'Samaypur Badli is a residential area of North-West Delhi near Rohini and Shahbad Dairy.'],
  ['Keshav Puram', 'rohini', 'Keshav Puram is a residential area of North-West Delhi between Netaji Subhash Place and Shastri Nagar.'],
  ['Tri Nagar', 'rohini', 'Tri Nagar is a residential area of North-West Delhi near Keshav Puram and Inderlok.'],
  ['Shastri Nagar', 'campus', 'Shastri Nagar is a residential area of North Delhi near Inderlok and Keshav Puram.'],
  ['Inderlok', 'campus', 'Inderlok is a well-connected residential area of North Delhi near Shastri Nagar.'],
  ['Netaji Subhash Place', 'rohini', 'Netaji Subhash Place is a major commercial and office hub of North-West Delhi, close to Pitampura and our Rohini centre.'],
  ['Haiderpur', 'rohini', 'Haiderpur is a residential area of North-West Delhi near Shalimar Bagh and Rohini.'],
  ['Saraswati Vihar', 'rohini', 'Saraswati Vihar is a residential colony beside Pitampura, close to our Rohini centre.'],
  ['Kohat Enclave', 'rohini', 'Kohat Enclave is a residential area next to Pitampura in North-West Delhi, close to our Rohini centre.'],
  ['Rani Bagh', 'rohini', 'Rani Bagh is a residential and market area beside Pitampura and Shakurpur in North-West Delhi.'],
  ['Shakurpur', 'rohini', 'Shakurpur is a residential area of North-West Delhi near Rani Bagh and Netaji Subhash Place.'],
  ['Paschim Puri', 'outerRohini', 'Paschim Puri is a residential area of West Delhi near Paschim Vihar.'],
  ['Karala', 'outerRohini', 'Karala is an urban village in outer North-West Delhi, west of Rohini.'],
  ['Kanjhawala', 'outerRohini', 'Kanjhawala is a village and residential area in outer North-West Delhi.'],
  ['Nithari', 'outerRohini', 'Nithari is a residential area in outer North-West Delhi near Kirari and Aman Vihar.'],
  ['Aman Vihar', 'outerRohini', 'Aman Vihar is a residential area near Kirari and Sultanpuri in North-West Delhi.'],
  ['Hudson Lane (Vijay Nagar)', 'campus', 'Hudson Lane in Vijay Nagar is a lively student area right next to the Delhi University North Campus.'],
  ['Timarpur', 'campus', 'Timarpur is a residential area of North Delhi near Civil Lines and the University North Campus.'],
  ['Civil Lines', 'campus', 'Civil Lines is one of North Delhi’s oldest residential areas, close to the Delhi University North Campus.'],
  ['Sonipat', 'haryana', 'Sonipat in Haryana is a growing NCR city and education hub, home to several well-known universities.'],
];
